export const allOptions = [
  {
    id: 1,
    name: "All Promo",
  },
  {
    id: 2,
    name: "Special Menu",
    value: "250+",
  },
  {
    id: 3,
    name: "Main Food",
    value: 65,
  },
  {
    id: 4,
    name: "Drinks",
  },
  {
    id: 5,
    name: "Appetizer",
  },
  {
    id: 6,
    name: "dessert",
  },
  {
    id: 7,
    name: "Fast Foods",
  },
];

export const all_Items = [
  {
    id: 1,
    url: "https://t4.ftcdn.net/jpg/05/81/48/89/240_F_581488930_jSWEv0Pd7fXqvV7llro7YCD3l0JfHdEA.jpg",
    title: "Chicken Biryani",
    rating: 4,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 10.0,
  },
  {
    id: 2,
    url: "https://t3.ftcdn.net/jpg/06/16/49/64/240_F_616496498_o5pbMU1Bw8FoUX3ZY5D9rOKfTa2ZkAya.jpg",
    title: "Momos",
    rating: 3.8,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 15.0,
  },
  {
    id: 3,
    url: "https://t3.ftcdn.net/jpg/06/20/60/30/240_F_620603097_9gGKtJXGYbBhAZL4e18aMjrQOzjX4GRO.jpg",
    title: "Butter Paneer",
    rating: 2.5,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 25.0,
  },
  {
    id: 4,
    url: "https://t4.ftcdn.net/jpg/05/81/48/89/240_F_581488930_jSWEv0Pd7fXqvV7llro7YCD3l0JfHdEA.jpg",
    title: "Chicken Biryani",
    rating: 4,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 10.0,
  },
  {
    id: 5,
    url: "https://t3.ftcdn.net/jpg/06/16/49/64/240_F_616496498_o5pbMU1Bw8FoUX3ZY5D9rOKfTa2ZkAya.jpg",
    title: "Momos",
    rating: 3.8,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 15.0,
  },
  {
    id: 6,
    url: "https://t3.ftcdn.net/jpg/06/20/60/30/240_F_620603097_9gGKtJXGYbBhAZL4e18aMjrQOzjX4GRO.jpg",
    title: "Butter Paneer",
    rating: 2.5,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 25.0,
  },
  {
    id: 7,
    url: "https://t4.ftcdn.net/jpg/05/81/48/89/240_F_581488930_jSWEv0Pd7fXqvV7llro7YCD3l0JfHdEA.jpg",
    title: "Chicken Biryani",
    rating: 4,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 10.0,
  },
  {
    id: 8,
    url: "https://t3.ftcdn.net/jpg/06/16/49/64/240_F_616496498_o5pbMU1Bw8FoUX3ZY5D9rOKfTa2ZkAya.jpg",
    title: "Momos",
    rating: 3.8,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 15.0,
  },
  {
    id: 9,
    url: "https://t3.ftcdn.net/jpg/06/20/60/30/240_F_620603097_9gGKtJXGYbBhAZL4e18aMjrQOzjX4GRO.jpg",
    title: "Butter Paneer",
    rating: 2.5,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 25.0,
  },
  {
    id: 10,
    url: "https://t4.ftcdn.net/jpg/05/81/48/89/240_F_581488930_jSWEv0Pd7fXqvV7llro7YCD3l0JfHdEA.jpg",
    title: "Chicken Biryani",
    rating: 4,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 10.0,
  },
  {
    id: 11,
    url: "https://t3.ftcdn.net/jpg/06/16/49/64/240_F_616496498_o5pbMU1Bw8FoUX3ZY5D9rOKfTa2ZkAya.jpg",
    title: "Momos",
    rating: 3.8,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 15.0,
  },
  {
    id: 12,
    url: "https://t3.ftcdn.net/jpg/06/20/60/30/240_F_620603097_9gGKtJXGYbBhAZL4e18aMjrQOzjX4GRO.jpg",
    title: "1st Page last item",
    rating: 2.5,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 25.0,
  },
  {
    id: 13,
    url: "https://t4.ftcdn.net/jpg/05/81/48/89/240_F_581488930_jSWEv0Pd7fXqvV7llro7YCD3l0JfHdEA.jpg",
    title: "Chicken Biryani",
    rating: 4,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 10.0,
  },
  {
    id: 14,
    url: "https://t3.ftcdn.net/jpg/06/16/49/64/240_F_616496498_o5pbMU1Bw8FoUX3ZY5D9rOKfTa2ZkAya.jpg",
    title: "Momos",
    rating: 3.8,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 15.0,
  },
  {
    id: 15,
    url: "https://t3.ftcdn.net/jpg/06/20/60/30/240_F_620603097_9gGKtJXGYbBhAZL4e18aMjrQOzjX4GRO.jpg",
    title: "Butter Paneer",
    rating: 2.5,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 25.0,
  },
  {
    id: 15,
    url: "https://t4.ftcdn.net/jpg/05/81/48/89/240_F_581488930_jSWEv0Pd7fXqvV7llro7YCD3l0JfHdEA.jpg",
    title: "Chicken Biryani",
    rating: 4,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 10.0,
  },
  {
    id: 16,
    url: "https://t3.ftcdn.net/jpg/06/16/49/64/240_F_616496498_o5pbMU1Bw8FoUX3ZY5D9rOKfTa2ZkAya.jpg",
    title: "Momos",
    rating: 3.8,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 15.0,
  },
  {
    id: 17,
    url: "https://t3.ftcdn.net/jpg/06/20/60/30/240_F_620603097_9gGKtJXGYbBhAZL4e18aMjrQOzjX4GRO.jpg",
    title: "Butter Paneer",
    rating: 2.5,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 25.0,
  },
  {
    id: 18,
    url: "https://t4.ftcdn.net/jpg/05/81/48/89/240_F_581488930_jSWEv0Pd7fXqvV7llro7YCD3l0JfHdEA.jpg",
    title: "Chicken Biryani",
    rating: 4,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 10.0,
  },
  {
    id: 19,
    url: "https://t3.ftcdn.net/jpg/06/16/49/64/240_F_616496498_o5pbMU1Bw8FoUX3ZY5D9rOKfTa2ZkAya.jpg",
    title: "Momos",
    rating: 3.8,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 15.0,
  },
  {
    id: 20,
    url: "https://t3.ftcdn.net/jpg/06/20/60/30/240_F_620603097_9gGKtJXGYbBhAZL4e18aMjrQOzjX4GRO.jpg",
    title: "Butter Paneer",
    rating: 2.5,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 25.0,
  },
  {
    id: 21,
    url: "https://t4.ftcdn.net/jpg/05/81/48/89/240_F_581488930_jSWEv0Pd7fXqvV7llro7YCD3l0JfHdEA.jpg",
    title: "Chicken Biryani",
    rating: 4,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 10.0,
  },
  {
    id: 22,
    url: "https://t3.ftcdn.net/jpg/06/16/49/64/240_F_616496498_o5pbMU1Bw8FoUX3ZY5D9rOKfTa2ZkAya.jpg",
    title: "Momos",
    rating: 3.8,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 15.0,
  },
  {
    id: 23,
    url: "https://t3.ftcdn.net/jpg/06/20/60/30/240_F_620603097_9gGKtJXGYbBhAZL4e18aMjrQOzjX4GRO.jpg",
    title: "Butter Paneer",
    rating: 2.5,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 25.0,
  },
  {
    id: 24,
    url: "https://t4.ftcdn.net/jpg/05/81/48/89/240_F_581488930_jSWEv0Pd7fXqvV7llro7YCD3l0JfHdEA.jpg",
    title: "2nd page last item",
    rating: 4,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 10.0,
  },
  {
    id: 25,
    url: "https://t3.ftcdn.net/jpg/06/16/49/64/240_F_616496498_o5pbMU1Bw8FoUX3ZY5D9rOKfTa2ZkAya.jpg",
    title: "25th item",
    rating: 3.8,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 15.0,
  },
  {
    id: 26,
    url: "https://t3.ftcdn.net/jpg/06/20/60/30/240_F_620603097_9gGKtJXGYbBhAZL4e18aMjrQOzjX4GRO.jpg",
    title: "Butter Paneer",
    rating: 2.5,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 25.0,
  },
  {
    id: 27,
    url: "https://t4.ftcdn.net/jpg/05/81/48/89/240_F_581488930_jSWEv0Pd7fXqvV7llro7YCD3l0JfHdEA.jpg",
    title: "Chicken Biryani",
    rating: 4,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 10.0,
  },
  {
    id: 28,
    url: "https://t3.ftcdn.net/jpg/06/16/49/64/240_F_616496498_o5pbMU1Bw8FoUX3ZY5D9rOKfTa2ZkAya.jpg",
    title: "Momos",
    rating: 3.8,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 15.0,
  },
  {
    id: 29,
    url: "https://t3.ftcdn.net/jpg/06/20/60/30/240_F_620603097_9gGKtJXGYbBhAZL4e18aMjrQOzjX4GRO.jpg",
    title: "Butter Paneer",
    rating: 2.5,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 25.0,
  },
  {
    id: 30,
    url: "https://t4.ftcdn.net/jpg/05/81/48/89/240_F_581488930_jSWEv0Pd7fXqvV7llro7YCD3l0JfHdEA.jpg",
    title: "Chicken Biryani",
    rating: 4,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 10.0,
  },
  {
    id: 31,
    url: "https://t3.ftcdn.net/jpg/06/16/49/64/240_F_616496498_o5pbMU1Bw8FoUX3ZY5D9rOKfTa2ZkAya.jpg",
    title: "Momos",
    rating: 3.8,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 15.0,
  },
  {
    id: 32,
    url: "https://t3.ftcdn.net/jpg/06/20/60/30/240_F_620603097_9gGKtJXGYbBhAZL4e18aMjrQOzjX4GRO.jpg",
    title: "Butter Paneer",
    rating: 2.5,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 25.0,
  },
  {
    id: 33,
    url: "https://t4.ftcdn.net/jpg/05/81/48/89/240_F_581488930_jSWEv0Pd7fXqvV7llro7YCD3l0JfHdEA.jpg",
    title: "Second last item",
    rating: 4,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 10.0,
  },
  {
    id: 35,
    url: "https://t3.ftcdn.net/jpg/06/16/49/64/240_F_616496498_o5pbMU1Bw8FoUX3ZY5D9rOKfTa2ZkAya.jpg",
    title: "Momos",
    rating: 3.8,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 15.0,
  },
  {
    id: 36,
    url: "https://t3.ftcdn.net/jpg/06/20/60/30/240_F_620603097_9gGKtJXGYbBhAZL4e18aMjrQOzjX4GRO.jpg",
    title: "last item",
    rating: 2.5,
    desc: "Savor a fresh and wholesome salad featuring crisp greens, juicy cherry tomatoes, and creamy avocado tossed in a zesty lemon vinaigrette.",
    price: 25.0,
  },
];
